version: '2'
services:
  database:
    build:
      context: ./cp-produtos-database
    image: cp-produtos-database
    environment:
      MYSQL_ROOT_PASSWORD: senha-root
    ports:
    - 3306:3306
    restart: always
  webserver:
    build:
      context: .
      dockerfile: Dockerfile-webserver
    image: cp-produtos-webserver
    links:
    - database:cp-produtos-database
    ports:
    - 8080:8080
    restart: always